# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: spark/connect/base.proto for package 'spark.connect'
# Original file comments:
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'spark/connect/base_pb'

module Spark
  module Connect
    module SparkConnectService
      # Main interface for the SparkConnect service.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'spark.connect.SparkConnectService'

        # Executes a request that contains the query and returns a stream of [[Response]].
        #
        # It is guaranteed that there is at least one ARROW batch returned even if the result set is empty.
        rpc :ExecutePlan, ::Spark::Connect::ExecutePlanRequest, stream(::Spark::Connect::ExecutePlanResponse)
        # Analyzes a query and returns a [[AnalyzeResponse]] containing metadata about the query.
        rpc :AnalyzePlan, ::Spark::Connect::AnalyzePlanRequest, ::Spark::Connect::AnalyzePlanResponse
        # Update or fetch the configurations and returns a [[ConfigResponse]] containing the result.
        rpc :Config, ::Spark::Connect::ConfigRequest, ::Spark::Connect::ConfigResponse
        # Add artifacts to the session and returns a [[AddArtifactsResponse]] containing metadata about
        # the added artifacts.
        rpc :AddArtifacts, stream(::Spark::Connect::AddArtifactsRequest), ::Spark::Connect::AddArtifactsResponse
        # Check statuses of artifacts in the session and returns them in a [[ArtifactStatusesResponse]]
        rpc :ArtifactStatus, ::Spark::Connect::ArtifactStatusesRequest, ::Spark::Connect::ArtifactStatusesResponse
        # Interrupts running executions
        rpc :Interrupt, ::Spark::Connect::InterruptRequest, ::Spark::Connect::InterruptResponse
        # Reattach to an existing reattachable execution.
        # The ExecutePlan must have been started with ReattachOptions.reattachable=true.
        # If the ExecutePlanResponse stream ends without a ResultComplete message, there is more to
        # continue. If there is a ResultComplete, the client should use ReleaseExecute with
        rpc :ReattachExecute, ::Spark::Connect::ReattachExecuteRequest, stream(::Spark::Connect::ExecutePlanResponse)
        # Release an reattachable execution, or parts thereof.
        # The ExecutePlan must have been started with ReattachOptions.reattachable=true.
        # Non reattachable executions are released automatically and immediately after the ExecutePlan
        # RPC and ReleaseExecute may not be used.
        rpc :ReleaseExecute, ::Spark::Connect::ReleaseExecuteRequest, ::Spark::Connect::ReleaseExecuteResponse
        # Release a session.
        # All the executions in the session will be released. Any further requests for the session with
        # that session_id for the given user_id will fail. If the session didn't exist or was already
        # released, this is a noop.
        rpc :ReleaseSession, ::Spark::Connect::ReleaseSessionRequest, ::Spark::Connect::ReleaseSessionResponse
        # FetchErrorDetails retrieves the matched exception with details based on a provided error id.
        rpc :FetchErrorDetails, ::Spark::Connect::FetchErrorDetailsRequest, ::Spark::Connect::FetchErrorDetailsResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
