# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spark/connect/ml_common.proto

require 'google/protobuf'

require 'spark/connect/expressions_pb'


descriptor_data = "\n\x1dspark/connect/ml_common.proto\x12\rspark.connect\x1a\x1fspark/connect/expressions.proto\"\x91\x01\n\x08MlParams\x12\x33\n\x06params\x18\x01 \x03(\x0b\x32#.spark.connect.MlParams.ParamsEntry\x1aP\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.spark.connect.Expression.Literal:\x02\x38\x01\"\xff\x01\n\nMlOperator\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12\x34\n\x04type\x18\x03 \x01(\x0e\x32&.spark.connect.MlOperator.OperatorType\"\x9f\x01\n\x0cOperatorType\x12\x1d\n\x19OPERATOR_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17OPERATOR_TYPE_ESTIMATOR\x10\x01\x12\x1d\n\x19OPERATOR_TYPE_TRANSFORMER\x10\x02\x12\x1b\n\x17OPERATOR_TYPE_EVALUATOR\x10\x03\x12\x17\n\x13OPERATOR_TYPE_MODEL\x10\x04\"\x17\n\tObjectRef\x12\n\n\x02id\x18\x01 \x01(\tB6\n\x1eorg.apache.spark.connect.protoP\x01Z\x12internal/generatedb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Spark
  module Connect
    MlParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spark.connect.MlParams").msgclass
    MlOperator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spark.connect.MlOperator").msgclass
    MlOperator::OperatorType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spark.connect.MlOperator.OperatorType").enummodule
    ObjectRef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spark.connect.ObjectRef").msgclass
  end
end
