# frozen_string_literal: true

# Loads the generated Spark Connect protobuf/gRPC stubs and exposes them under a
# convenient, stable alias.
#
# The stubs are generated by `grpc_tools_ruby_protoc` from the vendored
# `proto/spark/connect/*.proto` files (see the `proto:generate` Rake task). The
# generated files `require` each other using paths rooted at
# `lib/spark_connect/proto` (e.g. `require "spark/connect/base_pb"`), so that
# directory must be on the load path before they are required.
proto_root = File.expand_path("proto", __dir__)
$LOAD_PATH.unshift(proto_root) unless $LOAD_PATH.include?(proto_root)

require "spark/connect/base_pb"
require "spark/connect/base_services_pb"
require "spark/connect/catalog_pb"
require "spark/connect/commands_pb"
require "spark/connect/common_pb"
require "spark/connect/expressions_pb"
require "spark/connect/relations_pb"
require "spark/connect/types_pb"
require "spark/connect/ml_pb"
require "spark/connect/ml_common_pb"

module SparkConnect
  # All generated Spark Connect protobuf message classes and the gRPC service
  # stub live under the `Spark::Connect` namespace (derived from the protobuf
  # package `spark.connect`). `SparkConnect::Proto` is an alias that keeps the
  # rest of the codebase decoupled from that detail and reads clearly, e.g.
  # `SparkConnect::Proto::Relation` or `SparkConnect::Proto::Expression`.
  Proto = ::Spark::Connect
end
